#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems
# installed from the root of your application.

APP_PATH = File.expand_path('../config/application', __dir__)
require File.expand_path('../config/boot', __dir__)
require 'rails/commands'
